One branch to rule them all
NSLS-II/lsdc pull request #199
Opened 2022-02-28 15:57 UTC by JunAishima

This branch is a combination of master (descendant of current AMX/FMX code), scans-ophyd-bluesky (FMX Bluesky work), and nyx_ophyd (NYX Bluesky work).

it will be used as the base for future nyx_ophyd to continue Bluesky development for experiments on NYX, and for adapting the combined code for use on AMX/FMX.

Currently a draft request that is more informational for what the branch is meant to be used for than necessarily one to be merged into master.

2022-02-28 21:59 UTC, RobertSchaffer1 commented
I'll start (likely quite slowly!) going through this, is there any particular part I should look at first?

2022-02-28 22:00 UTC, RobertSchaffer1 commented on beamline_lib.py
> +import gov_lib
Probably don't need this, based on the commented code below?

2022-02-28 22:02 UTC, RobertSchaffer1 commented on config_params.py
> +DETECTOR_OBJECT_TYPE_LSDC = "lsdc"  # using det_lib
I feel like these three should go above somewhere?

2022-02-28 22:06 UTC, JunAishima commented
> I'll start (likely quite slowly!) going through this, is there any particular part I should look at first?

you have probably seen a lot of the code by now, so the merge points are the most critical to make sure I didn't make any mistakes when bringing master+scans_ophyd_bluesky together, and then the merge with nyx_ophyd.

Remember that you can see the branch history graphically by looking at github.com -> LSDC -> Insights -> Network

2022-03-02 22:04 UTC, RobertSchaffer1 commented
> > I'll start (likely quite slowly!) going through this, is there any particular part I should look at first?
> 
> you have probably seen a lot of the code by now, so the merge points are the most critical to make sure I didn't make any mistakes when bringing master+scans_ophyd_bluesky together, and then the merge with nyx_ophyd.
> 
> Remember that you can see the branch history graphically by looking at github.com -> LSDC -> Insights -> Network

Makes a lot of sense... hmm, I'm really not sure what the best way to go about doing this is, look only at files that have been modified by multiple branches maybe? The issue with that approach is that a lot of the files are massive, and those are the ones that have been changed the most.

2022-05-04 19:16 UTC, mskinner5278 requested changes

2023-03-20 20:53 UTC, JunAishima commented
this draft is not too useful - especially now that things have moved on. as we have been reviewing code that goes into both master and one-branch, the merge should not be too difficult (though needs to be tested).

closing.

2023-03-20 20:53 UTC, closed without merging