Number of steps reduced in an interactive raster if the number of steps is less than 6
NSLS-II/lsdc pull request #371
Opened 2024-04-06 03:11 UTC by vshekar

When either dimension of an interactive raster is 5 or less motors get stuck after the first row (potentially a zebra problem).
To prevent this, the PR progressively reduces the step size until both dimensions have atleast 6 steps.

If the step size is 1 micron and is still < 6, no raster will be added

2024-04-16 18:13 UTC, JunAishima requested changes
the minimum size of raster should be configurable - I know NYX had issues that required a minimum size of 2 (though fixed recently).

2024-04-17 20:16 UTC, vshekar commented
Minimum size added to config_params: [eaff8ad](https://github.com/NSLS-II/lsdc/pull/371/commits/eaff8ad1eb1a941bd3d379921f93a71ad667563c)

2024-04-22 16:06 UTC, JunAishima commented on gui/control_main.py
> +            print(numsteps_h, numsteps_w, stepsize, stepsizeXPix, stepsizeYPix)
https://github.com/NSLS-II/lsdc/pull/371/commits/eaff8ad1eb1a941bd3d379921f93a71ad667563c

2024-04-22 16:06 UTC, JunAishima approved these changes

2024-04-22 16:21 UTC, merged