Vector setup
NSLS-II/lsdc pull request #54
Opened 2021-02-18 20:00 UTC by AbbyGi

Replaced `setPvDesc` calls for vector program device in `zebraDaq` function. Still needs to be tested.

2021-02-18 22:03 UTC, JunAishima requested changes
to me, everything looks good, except for the import.

please fix up the bluesky name in the import. I am happy otherwise.

2021-02-19 14:41 UTC, JunAishima commented
I am also concerned about this being rebased on my prepare_zebra branch (which has not been approved and merged yet). please consider this when reviewing.

while unconventional, doing this has the advantage of add onto my existing scans.py module.

2021-02-24 18:00 UTC, mrakitin approved these changes
I don't see major issues with that update.

As a side note, we actually need to enable linting (`flake8`+`black` auto-formatting).

2021-02-24 18:51 UTC, JunAishima commented on scans.py
> +       yield from bps.wait(RESET_GROUP)
OK, we have chatted in the weekly meeting and it is clear that I must have misunderstood that I would need to do abs_set and wait before sleep. it is now obvious to me that I didn't need to do this. Will put in a commit to fix this

2021-02-24 20:41 UTC, JunAishima commented on scans.py
> +       yield from bps.wait(RESET_GROUP)
fixed with https://github.com/NSLS-II/lsdc/pull/54/commits/ea1fa36b3c349c42944c0b296a52678388af8601

2021-03-05 15:04 UTC, mrakitin commented on scans.py
> +    yield from bps.wait(VECTOR_SCAN_GROUP)
This place should also be resolved to use `bps.mv(...)` instead.

2021-03-08 21:04 UTC, JunAishima approved these changes

2021-03-09 05:13 UTC, mrakitin approved these changes

2021-03-09 17:05 UTC, merged